name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -workspace 'MarvelSuperHeroes.xcworkspace' -scheme 'MarvelSuperHeroes' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
    - name: Run tests
      run: swift test -v
